"""PDF report generation using ReportLab."""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER

from app.schemas import AuditReport, Severity
from app.core.logging import get_logger

logger = get_logger(__name__)


class PDFReportGenerator:
    """Generates PDF reports from audit results."""

    def __init__(self, report: AuditReport):
        self.report = report
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """
        IMPORTANT:
        getSampleStyleSheet() already contains 'Title', 'BodyText', etc.
        Adding those again raises KeyError.
        Also StyleSheet1 doesn't support item assignment, so we can't replace.
        So we define unique names and use them.
        """
        self.styles.add(ParagraphStyle(
            name='PR_Title',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1a1a2e'),
        ))

        self.styles.add(ParagraphStyle(
            name='PR_SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#16213e'),
        ))

        self.styles.add(ParagraphStyle(
            name='PR_SubSection',
            parent=self.styles['Heading3'],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=colors.HexColor('#0f3460'),
        ))

        self.styles.add(ParagraphStyle(
            name='PR_BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
        ))

        self.styles.add(ParagraphStyle(
            name='PR_SmallText',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
        ))

        # Used only for the centered score line
        self.styles.add(ParagraphStyle(
            name='PR_Score',
            parent=self.styles['Normal'],
            fontSize=18,
            alignment=TA_CENTER,
        ))

    def generate(self) -> bytes:
        """Generate PDF and return as bytes."""
        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        story = []

        # Title
        story.append(Paragraph("Production Readiness Audit Report", self.styles['PR_Title']))
        story.append(Spacer(1, 10))

        # Summary
        story.extend(self._build_summary_section())
        story.append(Spacer(1, 20))

        # Score breakdown
        story.extend(self._build_score_section())
        story.append(PageBreak())

        # Detailed findings
        story.extend(self._build_findings_section())

        # Recommendations
        story.append(PageBreak())
        story.extend(self._build_recommendations_section())

        # Footer
        story.append(Spacer(1, 30))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        story.append(Paragraph(
            f"Generated by ProdReady Audit on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            self.styles['PR_SmallText']
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    def _build_summary_section(self):
        elements = []

        info_data = [
            ["Target URL:", self.report.url],
            ["Audit ID:", self.report.audit_id],
            ["Started:", self.report.started_at.strftime("%Y-%m-%d %H:%M UTC")],
            ["Duration:", f"{self.report.duration_seconds:.1f} seconds" if self.report.duration_seconds else "N/A"],
            ["Pages Audited:", str(self.report.pages_audited)],
            ["Total Requests:", str(self.report.total_requests)],
        ]

        info_table = Table(info_data, colWidths=[100, 350])
        info_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#333333')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))

        elements.append(info_table)
        elements.append(Spacer(1, 20))

        score_color = self._get_score_color(self.report.score)
        elements.append(Paragraph(
            f"<b>Overall Score: <font color='{score_color}'>{self.report.score}/100 (Grade {self.report.grade})</font></b>",
            self.styles['PR_Score']
        ))

        elements.append(Spacer(1, 10))
        elements.append(Paragraph(self.report.summary, self.styles['PR_BodyText']))

        return elements

    def _build_score_section(self):
        elements = []
        elements.append(Paragraph("Score Breakdown", self.styles['PR_SectionHeader']))

        data = [["Category", "Score", "Issues"]]
        for cat in self.report.category_scores:
            data.append([cat.category, f"{cat.score}/{cat.max_score}", str(cat.issues_count)])

        table = Table(data, colWidths=[200, 100, 100])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ]))

        elements.append(table)
        return elements

    def _build_findings_section(self):
        elements = []
        elements.append(Paragraph("Detailed Findings", self.styles['PR_SectionHeader']))

        if self.report.console_errors:
            elements.append(Paragraph(
                f"Console Errors ({len(self.report.console_errors)})",
                self.styles['PR_SubSection']
            ))
            for error in self.report.console_errors[:10]:
                severity_color = self._get_severity_color(error.severity)
                elements.append(Paragraph(
                    f"<font color='{severity_color}'>[{error.severity.value.upper()}]</font> {self._escape_text(error.message[:200])}",
                    self.styles['PR_BodyText']
                ))
                elements.append(Paragraph(f"Page: {error.page_url}", self.styles['PR_SmallText']))
            if len(self.report.console_errors) > 10:
                elements.append(Paragraph(
                    f"... and {len(self.report.console_errors) - 10} more",
                    self.styles['PR_SmallText']
                ))

        if self.report.network_failures:
            elements.append(Paragraph(
                f"Network Failures ({len(self.report.network_failures)})",
                self.styles['PR_SubSection']
            ))
            data = [["URL", "Method", "Status", "Duration"]]
            for failure in self.report.network_failures[:10]:
                data.append([
                    self._truncate_url(failure.url, 40),
                    failure.method,
                    str(failure.status or failure.error or "Failed"),
                    f"{failure.duration_ms:.0f}ms" if failure.duration_ms else "N/A",
                ])

            table = Table(data, colWidths=[200, 50, 80, 70])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dc3545')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ]))
            elements.append(table)

        if self.report.security_hygiene:
            elements.append(Paragraph("Security Hygiene", self.styles['PR_SubSection']))
            https_status = "✓ HTTPS enabled" if self.report.security_hygiene.https_ok else "✗ HTTPS not enabled"
            elements.append(Paragraph(https_status, self.styles['PR_BodyText']))

            if self.report.security_hygiene.headers_missing:
                elements.append(Paragraph(
                    f"Missing headers: {', '.join(self.report.security_hygiene.headers_missing)}",
                    self.styles['PR_BodyText']
                ))
            if self.report.security_hygiene.headers_present:
                elements.append(Paragraph(
                    f"Present headers: {', '.join(self.report.security_hygiene.headers_present)}",
                    self.styles['PR_SmallText']
                ))

        if self.report.accessibility_violations:
            elements.append(Paragraph(
                f"Accessibility Violations ({len(self.report.accessibility_violations)})",
                self.styles['PR_SubSection']
            ))
            for violation in self.report.accessibility_violations[:5]:
                elements.append(Paragraph(
                    f"<b>[{violation.impact.upper()}]</b> {violation.id}: {violation.description}",
                    self.styles['PR_BodyText']
                ))

        return elements

    def _build_recommendations_section(self):
        elements = []
        elements.append(Paragraph("Recommendations", self.styles['PR_SectionHeader']))

        if not self.report.recommended_fixes:
            elements.append(Paragraph("No critical recommendations. Great job!", self.styles['PR_BodyText']))
            return elements

        for i, fix in enumerate(self.report.recommended_fixes, 1):
            severity_color = self._get_severity_color(fix.severity)

            elements.append(Paragraph(
                f"<b>{i}. {fix.category}</b> <font color='{severity_color}'>[{fix.severity.value.upper()}]</font>",
                self.styles['PR_SubSection']
            ))
            elements.append(Paragraph(f"<b>Issue:</b> {fix.issue}", self.styles['PR_BodyText']))
            elements.append(Paragraph(f"<b>Fix:</b> {fix.recommendation}", self.styles['PR_BodyText']))

            if fix.affected_urls:
                elements.append(Paragraph(
                    f"Affected: {', '.join(fix.affected_urls[:3])}",
                    self.styles['PR_SmallText']
                ))

            elements.append(Spacer(1, 10))

        return elements

    def _get_score_color(self, score: int) -> str:
        if score >= 90:
            return '#28a745'
        elif score >= 75:
            return '#17a2b8'
        elif score >= 50:
            return '#ffc107'
        return '#dc3545'

    def _get_severity_color(self, severity: Severity) -> str:
        if severity == Severity.ERROR:
            return '#dc3545'
        elif severity == Severity.WARNING:
            return '#ffc107'
        return '#6c757d'

    def _escape_text(self, text: str) -> str:
        return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

    def _truncate_url(self, url: str, max_length: int) -> str:
        if len(url) <= max_length:
            return url
        return url[:max_length - 3] + "..."


def generate_pdf_report(report: AuditReport) -> bytes:
    generator = PDFReportGenerator(report)
    return generator.generate()


def save_pdf_report(report: AuditReport, path: str) -> str:
    pdf_bytes = generate_pdf_report(report)
    with open(path, 'wb') as f:
        f.write(pdf_bytes)
    logger.info(f"PDF report saved to {path}")
    return path
